### ISSUE TITLE
Geef we document een titel

### ISSUE THREAD

**Issue by zoepje** [Zortux/the-startup-responsive-interactieve-website#1]
https://github.com/Zortux/the-startup-responsive-interactieve-website/blob/5f323bd180f160f840e2668d491729372a95591e/index.html#L8

Je hebt het `titel` element leeg gelaten, geef je document eens een naam.

Lees meer over het titel element https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

**Comment by Zortux** [comment]
Ik heb de issue opgelost. Ik heb een titel gegeven.
