### ISSUE TITLE
Image heeft geen alt

### ISSUE THREAD

**Issue by zoepje** [Zortux/the-startup-responsive-interactieve-website#2]
https://github.com/Zortux/the-startup-responsive-interactieve-website/blob/5f323bd180f160f840e2668d491729372a95591e/index.html#L11

Je image heeft geen alt. Met een alt maak je je website toegankelijker voor mensen die een screenreader gebruiken.

Je kunt hier meer lezen over image en alt:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Zortux** [comment]
Ik heb de img element een alt attribuut gegeven. Hier bij heb ik de issue gefixt.
